// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJt3JayTQi1c76BvXHa32c4mb2lipTYTg',
    appId: '1:128829525596:web:09fe1ddff5513f8cb26099',
    messagingSenderId: '128829525596',
    projectId: 'music-rock-eeb82',
    authDomain: 'music-rock-eeb82.firebaseapp.com',
    storageBucket: 'music-rock-eeb82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI9pPOo2blPL2JkILJ607Nj1PYpytP4qY',
    appId: '1:128829525596:android:5612eda97472f870b26099',
    messagingSenderId: '128829525596',
    projectId: 'music-rock-eeb82',
    storageBucket: 'music-rock-eeb82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmRzcif9I5fKtcq2WvNXWGnCCWKrTYk2A',
    appId: '1:128829525596:ios:e7918430a5333105b26099',
    messagingSenderId: '128829525596',
    projectId: 'music-rock-eeb82',
    storageBucket: 'music-rock-eeb82.firebasestorage.app',
    iosBundleId: 'com.example.musicRock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmRzcif9I5fKtcq2WvNXWGnCCWKrTYk2A',
    appId: '1:128829525596:ios:e7918430a5333105b26099',
    messagingSenderId: '128829525596',
    projectId: 'music-rock-eeb82',
    storageBucket: 'music-rock-eeb82.firebasestorage.app',
    iosBundleId: 'com.example.musicRock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJt3JayTQi1c76BvXHa32c4mb2lipTYTg',
    appId: '1:128829525596:web:81d6026f9b246fe1b26099',
    messagingSenderId: '128829525596',
    projectId: 'music-rock-eeb82',
    authDomain: 'music-rock-eeb82.firebaseapp.com',
    storageBucket: 'music-rock-eeb82.firebasestorage.app',
  );
}
